### ISSUE TITLE
More docs needed

### ISSUE THREAD

**Issue by officialpatterson** [i-net-software/JWebAssembly#1]
I like the project, but I'm finding it hard to get my head around it - is the project finished?

**Comment by Horcrux7** [comment]
Thanks for your interest. I have start the project only 3 weeks ago. Currently it is in a very early state. I have work on a test framework first. If you want try it then you should to wait some weeks. The code for compiling look like:

```
            File wasmFile = newFile( "test.wasm" );
            JWebAssembly wasm = new JWebAssembly();
            for( Class<?> clazz : classes ) {
                URL url = clazz.getResource( '/' + clazz.getName().replace( '.', '/' ) + ".class" );
                wasm.addFile( url );
            }
            wasm.compileToBinary( wasmFile );
```

**Comment by hohwille** [comment]
Awesome. Of course just a very minimal PoC but this gives us hope that some fine day pain will end and one can do full-stack development again with reasonable languages like Java (or C# - there are also cross-compilers arising for that).
The recent dual language with redundant code for model, validation, logic, service, etc. really sucks. The future is ahead. Thanks for your brave work. Actually I would love to see projects like this driven by Oracle backed with tons of developers to empower their Java. The question will also be if a cross-compiler written in 100% Java will scale for large projects and how the turn-around for developers will be. If I have a large client project and will have to wait for the compiler to rebuild my entire code-base for a small change then all will fall into peaces just like GWT did even though it was also a powerful case.

**Comment by Horcrux7** [comment]
@hohwille Sorry, it look like I have oversee your comment. A new ticket can be better.

Large projects: The continue compiler and the hot replace compiler of Java was a very rare stroke of luck. If you want compile in other languages like a C++ project you need also wait for compile the completely project.

I think the solution will be modularization. Writing a large count of small webassemblies.

Oracle: Because Oracle has only interest on backends and servers I think this will never occur.

full-stack development: You are welcome to work on it. More as the pure compiler and the Gradle plugin can we not handle. Very nice will be an IDE integration.
